# Generated by Django 5.0.6 on 2024-05-28 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('contacto', models.CharField(max_length=100)),
                ('disponibilidad', models.CharField(choices=[('dis', 'Disponible'), ('ago', 'Agotado')], default='disponible', max_length=100)),
                ('proovedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.proovedor')),
            ],
        ),
    ]
